import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SidMenu from "@/components/admin/SideMenu";
import Header from "@/components/admin/Header";
import ToastProvider from "@/components/admin/ToastProvider";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




async function verifyAdmin() {
  try {
    const cookieStore = await cookies();

    const cookieHeader = cookieStore
      .getAll()
      .map((c) => `${c.name}=${c.value}`)
      .join("; ");

    const res = await fetch("http://localhost:5000/admin/auth/me", {
      headers: {
        Cookie: cookieHeader,
      },
      cache: "no-store",
    });

    return res.ok;
  } catch {
    return false;
  }
}



export default async function RootLayout({ children }) {
    const isAdmin = await verifyAdmin();

  if (!isAdmin) {
    redirect("/admin/login");
  }
  return (
    // <html lang="en">
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
    
    <div className="w-full flex">
      <ToastProvider />
      <SidMenu />
      <div className="flex-1 bg-white-200">
        <Header />
        <div className="p-4 w-full">{children}</div>
      </div>
    </div>

    //   </body>
    // </html>
  );
}
