import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SidMenu from "@/components/admin/SideMenu";
import Header from "@/components/admin/Header";
import ToastProvider from "@/components/admin/ToastProvider";
import AdminAuthGuard from "@/components/admin/AdminAuthGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AdminAuthGuard>
      <div className="w-full flex">
        <ToastProvider />
        <SidMenu />
        <div className="flex-1 bg-white-200">
          <Header />
          <div className="p-4 w-full">{children}</div>
        </div>
      </div>
    </AdminAuthGuard>
  );
}