import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/website/Header";
import FooterServer from "@/components/website/FooterServer";
import StoreProvider from "@/redux/ReduxProvider";
import PageTransition from "@/components/animations/PageTransition";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ishop - Your One-Stop Tech Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    //   <head>
    //     {/* Prevent extensions/devtools from injecting and causing hydration errors */}
    //     <meta name="next-disable-react-devtools" content="true" />
    //   </head>

    // <body
    //   className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    // >
    <StoreProvider>
      <Header />
      <PageTransition>
      {children}
    </PageTransition>
      <FooterServer />
    </StoreProvider>
    // </body>
    // </html>
  );
}
