
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import ReduxProvider from "@/redux/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ishop - Your One-Stop Tech Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Prevent extensions/devtools from injecting and causing hydration errors */}
        <meta name="next-disable-react-devtools" content="true" />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <ReduxProvider>
          
          {children}
          
        </ReduxProvider>
      </body>
    </html>
  );
}
